version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: postgres-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: testDB
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
